# Generated by Django 4.1.1 on 2022-11-13 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0012_grupo_slug'),
        ('appPartido', '0006_alter_encuentro_clima_alter_encuentro_humedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuentro',
            name='competicion_id',
            field=models.ForeignKey(db_column='competicion_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='appCompeticion.competicion'),
            preserve_default=False,
        ),
    ]
