# Generated by Django 4.1.1 on 2022-11-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0007_encuentro_competicion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
