# Generated by Django 4.1.1 on 2022-11-13 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0008_alter_encuentro_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='detalle_encuentro',
        ),
    ]
