# Generated by Django 4.1.1 on 2022-11-13 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0007_remove_alineacion_equipo_detalle_encuentro_id'),
        ('appPartido', '0009_delete_detalle_encuentro'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuentro',
            name='equipo_local',
            field=models.ForeignKey(db_column='equipo_local', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipo_local', to='appEquipo.equipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuentro',
            name='equipo_visita',
            field=models.ForeignKey(db_column='equipo_visita', default=2, on_delete=django.db.models.deletion.CASCADE, related_name='equipo_visita', to='appEquipo.equipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuentro',
            name='formacion_local',
            field=models.ForeignKey(db_column='formacion_local', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='formacion_local', to='appPartido.formacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuentro',
            name='formacion_visita',
            field=models.ForeignKey(db_column='formacion_visita', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='formacion_visita', to='appPartido.formacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuentro',
            name='resultado_goles_local',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuentro',
            name='resultado_goles_visita',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuentro',
            name='resultado_local',
            field=models.CharField(choices=[('G', 'GANADO'), ('E', 'EMPATADO'), ('P', 'PERDIDO')], default='G', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuentro',
            name='resultado_visita',
            field=models.CharField(choices=[('G', 'GANADO'), ('E', 'EMPATADO'), ('P', 'PERDIDO')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
