# Generated by Django 4.1.1 on 2022-11-14 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0010_alter_alineacion_options_and_more'),
        ('appPartido', '0011_encuentro_alineacion_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='alineacion_local',
            field=models.ForeignKey(blank=True, db_column='alineacion_local', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alineacion_local', to='appEquipo.alineacion'),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='alineacion_visita',
            field=models.ForeignKey(blank=True, db_column='alineacion_visita', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alineacion_visita', to='appEquipo.alineacion'),
        ),
    ]
