# Generated by Django 4.1.1 on 2022-11-14 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0013_alter_encuentro_formacion_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='sede_id',
            field=models.ForeignKey(blank=True, db_column='sede_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='appPartido.sede'),
        ),
    ]
