# Generated by Django 4.1.1 on 2022-11-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appContrato', '0005_persona_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='dorsal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='posicion_jugador',
            field=models.CharField(default='DELANTERO', max_length=30),
            preserve_default=False,
        ),
    ]
