# Generated by Django 4.1.1 on 2022-11-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appContrato', '0006_contrato_dorsal_contrato_posicion_jugador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.ImageField(blank=True, default='jugador/def_jugador.png', null=True, upload_to='jugador/foto/'),
        ),
    ]
