# Generated by Django 4.1.1 on 2022-11-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appContrato', '0009_alter_contrato_dorsal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='alias',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
