# Generated by Django 4.1.1 on 2022-11-11 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0006_alter_encuentro_clima_alter_encuentro_humedad'),
        ('appEquipo', '0005_equipo_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='alineacion_equipo',
            name='detalle_encuentro_id',
            field=models.ForeignKey(db_column='detalle_encuentro_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='appPartido.detalle_encuentro'),
            preserve_default=False,
        ),
    ]
