# Generated by Django 4.1.1 on 2022-11-13 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0006_alineacion_equipo_detalle_encuentro_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alineacion_equipo',
            name='detalle_encuentro_id',
        ),
    ]
