# Generated by Django 4.1.1 on 2022-11-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0008_alineacion_equipo_encuentro_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='alineacion',
            fields=[
                ('alineacion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_juego', models.DateField()),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='alineacion_equipo',
            name='encuentro_id',
        ),
    ]
