# Generated by Django 4.1.1 on 2022-11-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0005_competicion_fecha_fin_competicion_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='competicion',
            name='logo_competicion',
            field=models.ImageField(blank=True, null=True, upload_to='competicion/logo/'),
        ),
    ]
