# Generated by Django 4.1.1 on 2022-11-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0006_competicion_logo_competicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='logo_bandera',
            field=models.ImageField(blank=True, default='bandera/bandera_default.png', null=True, upload_to='bandera/'),
        ),
        migrations.AlterField(
            model_name='competicion',
            name='logo_competicion',
            field=models.ImageField(blank=True, default='competicion/logo/logo_default.png', null=True, upload_to='competicion/logo/'),
        ),
    ]
