# Generated by Django 4.1.1 on 2022-11-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0007_pais_logo_bandera_alter_competicion_logo_competicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='fase',
            fields=[
                ('fase_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
