# Generated by Django 4.1.1 on 2022-11-13 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0008_fase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fase',
            options={'verbose_name_plural': 'fase'},
        ),
        migrations.AddField(
            model_name='detalle_grupo',
            name='fase_id',
            field=models.ForeignKey(db_column='fase_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='appCompeticion.fase'),
            preserve_default=False,
        ),
    ]
