# Generated by Django 4.1.1 on 2022-11-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0009_alter_fase_options_detalle_grupo_fase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_grupo',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
