# Generated by Django 4.1.1 on 2022-11-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0011_remove_detalle_grupo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
